<?php
use Drupal\node\Entity\Node;
use Drupal\Core\Datetime\DrupalDateTime;

function nesea_pm_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'private_message_add_form') {
    $form['members']['widget']['target_id']['#attributes']['readonly'] = 'readonly';
    $form['#attached']['library'][] = 'nesea_pm/nesea_pm-form-js';
  }
  if ($form_id == 'block_user_form') {
    $form['banned_user']['#access'] = false;
    $form['submit']['#access'] = false;
  }
}
